apiVersion: v1
kind: ConfigMap
metadata:
  name: oficina-config
data:
  SPRING_DATASOURCE_URL: "REPLACE_WITH_RDS_JDBC_URL"
  SPRING_DATASOURCE_USERNAME: "oficina_admin"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_DOCKER_COMPOSE_ENABLED: "false"
  APP_PUBLIC_BASE_URL: "REPLACE_WITH_API_GATEWAY_URL"