apiVersion: apps/v1
kind: Deployment
metadata:
  name: oficina-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oficina-db
  template:
    metadata:
      labels:
        app: oficina-db
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: oficina-config
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: oficina-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: oficina-secrets
                  key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: oficina-db
spec:
  selector:
    app: oficina-db
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
