apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
stringData:
  POSTGRES_PASSWORD: CHANGE_ME
  JWT_SECRET: CHANGE_ME
  SPRING_MAIL_USERNAME: CHANGE_ME
  SPRING_MAIL_PASSWORD: CHANGE_ME
  APP_MAIL_FROM: CHANGE_ME
