apiVersion: v1
kind: Secret
metadata:
  name: oficina-secrets
type: Opaque
stringData:
  POSTGRES_DB: oficina_db
  POSTGRES_USER: oficina_user
  POSTGRES_PASSWORD: oficina_pass
  JWT_SECRET: oficina
  SPRING_MAIL_USERNAME: arnetoapi@gmail.com
  SPRING_MAIL_PASSWORD: vqdh sggf rhgi vfxc
  APP_MAIL_FROM: arnetoapi@gmail.com
  APP_PUBLIC_BASE_URL: http://localhost:8080
